import { Team, Match } from './common-types';

export const matches: Match[] = [
	{
		id: '0',
		lowerParentId: null,
		upperParentId: null,
		lowerTeamId: '0',
		upperTeamId: '1',
		lowerTeamScore: 0,
		upperTeamScore: 1,
		winner: 'upper',
	},
	{
		id: '1',
		lowerParentId: '4',
		upperParentId: '2',
		lowerTeamId: null,
		upperTeamId: null,
		lowerTeamScore: null,
		upperTeamScore: null,
		winner: null,
	},
	{
		id: '2',
		lowerParentId: null,
		upperParentId: '3',
		lowerTeamId: '12',
		upperTeamId: '14',
		lowerTeamScore: 2,
		upperTeamScore: 1,
		winner: null,
	},
	{
		id: '3',
		lowerParentId: null,
		upperParentId: null,
		lowerTeamId: '12',
		upperTeamId: '13',
		lowerTeamScore: 27,
		upperTeamScore: 5,
		winner: 'lower',
	},
	{
		id: '4',
		lowerParentId: '14',
		upperParentId: '5',
		lowerTeamId: null,
		upperTeamId: null,
		lowerTeamScore: null,
		upperTeamScore: null,
		winner: null,
	},
	{
		id: '5',
		lowerParentId: '6',
		upperParentId: '7',
		lowerTeamId: '10',
		upperTeamId: '8',
		lowerTeamScore: 4,
		upperTeamScore: 1,
		winner: 'lower',
	},
	{
		id: '6',
		lowerParentId: null,
		upperParentId: null,
		lowerTeamId: '10',
		upperTeamId: '11',
		lowerTeamScore: 7,
		upperTeamScore: 3,
		winner: 'lower',
	},
	{
		id: '7',
		lowerParentId: null,
		upperParentId: '8',
		lowerTeamId: '8',
		upperTeamId: '10',
		lowerTeamScore: 1,
		upperTeamScore: 0,
		winner: 'lower',
	},
	{
		id: '8',
		lowerParentId: null,
		upperParentId: null,
		lowerTeamId: '8',
		upperTeamId: '9',
		lowerTeamScore: 2,
		upperTeamScore: 1,
		winner: 'lower',
	},
	{
		id: '9',
		lowerParentId: '0',
		upperParentId: null,
		lowerTeamId: '2',
		upperTeamId: '1',
		lowerTeamScore: 2,
		upperTeamScore: 0,
		winner: 'lower',
	},
	{
		id: '10',
		lowerParentId: null,
		upperParentId: null,
		lowerTeamId: '3',
		upperTeamId: '4',
		lowerTeamScore: 1,
		upperTeamScore: 2,
		winner: 'upper',
	},
	{
		id: '11',
		lowerParentId: '10',
		upperParentId: '9',
		lowerTeamId: '4',
		upperTeamId: '2',
		lowerTeamScore: 3,
		upperTeamScore: 0,
		winner: 'lower',
	},
	{
		id: '12',
		lowerParentId: '11',
		upperParentId: null,
		lowerTeamId: '4',
		upperTeamId: '5',
		lowerTeamScore: 2,
		upperTeamScore: 2,
		winner: null,
	},
	{
		id: '13',
		lowerParentId: null,
		upperParentId: null,
		lowerTeamId: '6',
		upperTeamId: '7',
		lowerTeamScore: 1,
		upperTeamScore: 0,
		winner: 'lower',
	},
	{
		id: '14',
		lowerParentId: '13',
		upperParentId: '12',
		lowerTeamId: null,
		upperTeamId: null,
		lowerTeamScore: null,
		upperTeamScore: null,
		winner: null,
	},
];

export const teams: Team[] = [
	{
		id: '0',
		name: 'Team Project',
	},
	{
		id: '1',
		name: 'Team Agile Kidz',
	},
	{
		id: '2',
		name: 'Team Omega',
	},
	{
		id: '3',
		name: 'Team Lmao',
	},
	{
		id: '4',
		name: 'Team Mega',
	},
	{
		id: '5',
		name: 'Team Cnonq',
	},
	{
		id: '6',
		name: 'Team Kek',
	},
	{
		id: '7',
		name: 'Team Lul',
	},
	{
		id: '8',
		name: 'Team A',
	},
	{
		id: '9',
		name: 'Team B',
	},
	{
		id: '10',
		name: 'Team C',
	},
	{
		id: '11',
		name: 'Team D',
	},
	{
		id: '12',
		name: 'Team Epicett',
	},
	{
		id: '13',
		name: 'Team Epictvå',
	},
	{
		id: '14',
		name: 'Team Epictree',
	},
];
